title: SQLBits DevOps workshop
description: SQL projects and source control integration for SQL in Fabric, Azure SQL, and SQL Server

# jeklyl base settings
theme: minima
url: ""
baseurl: ""

# theme settings
perma_link: "https://sqlworkshop.makestuffgo.com/"
github_repo: "HeyMo0sh/SQLBits-DevOps-workshop"

header_pages:
  - LAB1/README.md
  - LAB2/README.md
  - LAB3/README.md
  - LAB4/README.md
